numerics: numerics.cpp define.cpp test.cpp numint.cpp mcint.cpp gradient.cpp functions.cpp parse.cpp
	g++ -o numerics -std=gnu++11 -Wall -Werror -ggdb3 numerics.cpp define.cpp test.cpp numint.cpp mcint.cpp gradient.cpp functions.cpp parse.cpp
clean:
	rm -f *~ numerics
